Add files via upload
√ Fix the error caused by GoogleAnalytics Plugin

A problem existed in the last one. It appears a [Internal JavaScript Error]:
<Uncaught TypeError: $tw.wiki.getTiddlerText is not a function>

I downloaded the one before the last one, which I uploaded last night.
I repeated the previous work, but this time no error happens.
Interessant.